import type { Category, Resource } from "./resources";

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, slug: "development-tools", name: "Development Tools", icon: "dev" },
  { id: 2, slug: "cloud-and-hosting", name: "Cloud & Hosting", icon: "cloud" },
  { id: 3, slug: "design-and-creative", name: "Design & Creative", icon: "design" },
  { id: 4, slug: "ai-and-machine-learning", name: "AI & Machine Learning", icon: "ai" },
  { id: 5, slug: "productivity", name: "Productivity", icon: "prod" },
  { id: 6, slug: "media-and-entertainment", name: "Media & Entertainment", icon: "media" },
  { id: 7, slug: "health-and-wellness", name: "Health & Wellness", icon: "health" },
  { id: 8, slug: "security-and-privacy", name: "Security & Privacy", icon: "security" },
  { id: 9, slug: "domains-and-web", name: "Domains & Web", icon: "domains" },
];

export const MOCK_RESOURCES: Resource[] = [
  {
    id: 1,
    slug: "github-copilot",
    name: "GitHub Copilot",
    tagline: "Free Copilot Student plan",
    description: "AI coding assistance for your next project. Autocomplete code, generate tests, and get real-time suggestions across all your favorite editors.",
    url: "https://education.github.com/pack",
    hasStaticClaimUrl: true,
    categoryId: 1,
    categorySlug: "development-tools",
    categoryName: "Development Tools",
    categoryIcon: "🛠️",
    tags: ["AI", "Web", "macOS", "Windows"],
    region: "Global",
    costType: "free",
    verificationNeeded: "github_student_pack",
    creditCardRequired: false,
    duration: "while_student",
    status: "active",
    lastVerifiedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: 2,
    slug: "jetbrains",
    name: "JetBrains",
    tagline: "All IDEs + AI credits",
    description: "Professional tools for learning and building. Free access to IntelliJ IDEA Ultimate, PyCharm Professional, WebStorm, and all JetBrains desktop IDEs.",
    url: "https://www.jetbrains.com/community/education/#students",
    hasStaticClaimUrl: true,
    categoryId: 1,
    categorySlug: "development-tools",
    categoryName: "Development Tools",
    categoryIcon: "🛠️",
    tags: ["macOS", "Windows", "Web"],
    region: "Global",
    costType: "free",
    verificationNeeded: "edu_email",
    creditCardRequired: false,
    duration: "one_year",
    status: "active",
    lastVerifiedAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    id: 3,
    slug: "figma",
    name: "Figma",
    tagline: "Free Pro plan",
    description: "Design, prototype and collaborate with your team. Get full access to Figma Professional features, unlimited version history, and shared team libraries.",
    url: "https://www.figma.com/education/",
    hasStaticClaimUrl: true,
    categoryId: 3,
    categorySlug: "design-and-creative",
    categoryName: "Design & Creative",
    categoryIcon: "🎨",
    tags: ["Design", "Web", "macOS", "Windows"],
    region: "Global",
    costType: "free",
    verificationNeeded: "student_id",
    creditCardRequired: false,
    duration: "one_year",
    status: "active",
    lastVerifiedAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
  },
  {
    id: 4,
    slug: "aws-free-tier",
    name: "AWS Free Tier",
    tagline: "Up to $200 in cloud credits",
    description: "Explore cloud services for your next project. Compute, storage, and database instances to build and host your applications on Amazon Web Services.",
    url: "https://aws.amazon.com/education/awseducate/",
    hasStaticClaimUrl: true,
    categoryId: 2,
    categorySlug: "cloud-and-hosting",
    categoryName: "Cloud & Hosting",
    categoryIcon: "☁️",
    tags: ["Cloud", "Web"],
    region: "Global",
    costType: "credits",
    verificationNeeded: "edu_email",
    creditCardRequired: false,
    duration: "one_year",
    status: "active",
    lastVerifiedAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    id: 5,
    slug: "spotify-premium-student",
    name: "Spotify Premium Student",
    tagline: "Up to 50% off Premium",
    description: "Ad-free music and offline listening for students. Includes discounted subscription access and bundled streaming entertainment where available.",
    url: "https://www.spotify.com/student/",
    hasStaticClaimUrl: true,
    categoryId: 6,
    categorySlug: "media-and-entertainment",
    categoryName: "Media & Entertainment",
    categoryIcon: "🎵",
    tags: ["Audio", "iOS", "Android", "macOS", "Windows"],
    region: "Global",
    costType: "discount",
    verificationNeeded: "student_id",
    creditCardRequired: true,
    duration: "while_student",
    status: "active",
    lastVerifiedAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    id: 6,
    slug: "bettersleep",
    name: "BetterSleep",
    tagline: "Premium Student Plan",
    description: "Sleep sounds, guided meditations and bedtime stories. Mixable ambient soundscapes to help students unwind, focus, and study better.",
    url: "https://www.bettersleep.com/",
    hasStaticClaimUrl: true,
    categoryId: 7,
    categorySlug: "health-and-wellness",
    categoryName: "Health & Wellness",
    categoryIcon: "🧘",
    tags: ["Wellness", "iOS", "Android"],
    region: "IN",
    costType: "discount",
    verificationNeeded: "none",
    creditCardRequired: true,
    duration: "one_year",
    status: "active",
    lastVerifiedAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    id: 7,
    slug: "notion-plus",
    name: "Notion Plus for Students",
    tagline: "Free Plus Plan for Education",
    description: "Organize coursework, personal projects, notes and task lists with unlimited blocks, file uploads, and 30-day page version history.",
    url: "https://www.notion.so/students",
    hasStaticClaimUrl: true,
    categoryId: 5,
    categorySlug: "productivity",
    categoryName: "Productivity",
    categoryIcon: "⚡",
    tags: ["Productivity", "Notes", "Web", "macOS", "Windows", "iOS", "Android"],
    region: "Global",
    costType: "free",
    verificationNeeded: "edu_email",
    creditCardRequired: false,
    duration: "while_student",
    status: "active",
    lastVerifiedAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
  {
    id: 8,
    slug: "vercel-pro",
    name: "Vercel Student Program",
    tagline: "Free Cloud Deployment & Analytics",
    description: "Deploy Next.js, React, and frontend web projects with custom domains, automatic preview URLs, edge functions, and speed insights.",
    url: "https://vercel.com/contact/sales/students",
    hasStaticClaimUrl: true,
    categoryId: 2,
    categorySlug: "cloud-and-hosting",
    categoryName: "Cloud & Hosting",
    categoryIcon: "☁️",
    tags: ["Cloud", "Deployment", "Web"],
    region: "Global",
    costType: "free",
    verificationNeeded: "github_student_pack",
    creditCardRequired: false,
    duration: "one_year",
    status: "active",
    lastVerifiedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: 9,
    slug: "digitalocean",
    name: "DigitalOcean Student Credits",
    tagline: "$200 Cloud Infrastructure Credits",
    description: "Build on Linux droplets, managed Kubernetes, App Platform, and PostgreSQL databases with $200 in platform credits for active students.",
    url: "https://www.digitalocean.com/github-students",
    hasStaticClaimUrl: true,
    categoryId: 2,
    categorySlug: "cloud-and-hosting",
    categoryName: "Cloud & Hosting",
    categoryIcon: "☁️",
    tags: ["Cloud", "Hosting", "Web"],
    region: "Global",
    costType: "credits",
    verificationNeeded: "github_student_pack",
    creditCardRequired: true,
    duration: "one_year",
    status: "active",
    lastVerifiedAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },
  {
    id: 10,
    slug: "namecheap",
    name: "Namecheap",
    tagline: "Free .me domain for 1 year",
    description: "Claim a free .me domain name and SSL certificate to host your personal portfolio, resume website, or developer showcase.",
    url: "https://nc.me/",
    hasStaticClaimUrl: true,
    categoryId: 9,
    categorySlug: "domains-and-web",
    categoryName: "Domains & Web",
    categoryIcon: "🌐",
    tags: ["Domains", "Web"],
    region: "Global",
    costType: "free",
    verificationNeeded: "github_student_pack",
    creditCardRequired: false,
    duration: "one_year",
    status: "active",
    lastVerifiedAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    id: 11,
    slug: "1password",
    name: "1Password Student",
    tagline: "1 year free password manager",
    description: "Store passwords, passkeys, credit cards, and sensitive student credentials securely across all devices with biometric unlock.",
    url: "https://github.blog/2021-09-08-1password-student-developer-pack/",
    hasStaticClaimUrl: true,
    categoryId: 8,
    categorySlug: "security-and-privacy",
    categoryName: "Security & Privacy",
    categoryIcon: "🔒",
    tags: ["Security", "macOS", "Windows", "iOS", "Android"],
    region: "Global",
    costType: "free",
    verificationNeeded: "github_student_pack",
    creditCardRequired: false,
    duration: "one_year",
    status: "active",
    lastVerifiedAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    id: 12,
    slug: "canva-education",
    name: "Canva for Education",
    tagline: "Free premium design tools",
    description: "Create pitch decks, presentations, social media graphics, posters, and resumes with millions of premium templates and assets.",
    url: "https://www.canva.com/education/",
    hasStaticClaimUrl: true,
    categoryId: 3,
    categorySlug: "design-and-creative",
    categoryName: "Design & Creative",
    categoryIcon: "🎨",
    tags: ["Design", "Graphics", "Web"],
    region: "IN",
    costType: "free",
    verificationNeeded: "edu_email",
    creditCardRequired: false,
    duration: "while_student",
    status: "active",
    lastVerifiedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
];
